<?php

namespace Database\Seeders;

use App\Enums\DayOfWeek;
use App\Models\AcademicTerm;
use App\Models\Room;
use App\Models\Schedule;
use Illuminate\Database\Seeder;

class ScheduleSeeder extends Seeder
{
    public function run(): void
    {
        $term    = AcademicTerm::where('is_current', true)->firstOrFail();
        $adminId = 1;
        
        // Key by name
        $rooms = Room::pluck('id', 'name');

        // ------------------------------------------------------------
        // 6 sections across 4 year levels — demonstration data
        // ------------------------------------------------------------
        $schedules = [

            // BSCPE 1-1 (1st Year)
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'GEED 101',
                'subject_title'   => 'Understanding the Self',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Santos',
                'day_of_week'     => DayOfWeek::Monday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'MATH 101',
                'subject_title'   => 'Calculus 1',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Reyes',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'MATH 101',
                'subject_title'   => 'Calculus 1',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Reyes',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'PHYS 101',
                'subject_title'   => 'Physics for Engineers',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Bautista',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 101',
                'subject_title'   => 'Introduction to Computing',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Cruz',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '13:00:00',
                'end_time'        => '16:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'GEED 102',
                'subject_title'   => 'Readings in Philippine History',
                'section'         => 'BSCPE 1-1',
                'instructor_name' => 'Prof. Torres',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],

            // BSCPE 2-1 (2nd Year, Section 1) 
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 201',
                'subject_title'   => 'Computer Programming 2',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Garcia',
                'day_of_week'     => DayOfWeek::Monday,
                'start_time'      => '07:30:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 2',
                'subject_code'    => 'CMPE 202',
                'subject_title'   => 'Data Structures and Algorithms',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Lim',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '13:00:00',
                'end_time'        => '16:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'MATH 201',
                'subject_title'   => 'Differential Equations',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Navarro',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 203',
                'subject_title'   => 'Logic Circuits and Switching Theory',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Villanueva',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 2',
                'subject_code'    => 'CMPE 203L',
                'subject_title'   => 'Logic Circuits Lab',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Villanueva',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '07:30:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'ENGG 201',
                'subject_title'   => 'Engineering Economics',
                'section'         => 'BSCPE 2-1',
                'instructor_name' => 'Prof. Aquino',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],

            // BSCPE 2-2 (2nd Year, Section 2) 
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 201',
                'subject_title'   => 'Computer Programming 2',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Garcia',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 202',
                'subject_title'   => 'Data Structures and Algorithms',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Lim',
                'day_of_week'     => DayOfWeek::Monday,
                'start_time'      => '13:30:00',
                'end_time'        => '16:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'MATH 201',
                'subject_title'   => 'Differential Equations',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Navarro',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '10:30:00',
                'end_time'        => '12:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 203',
                'subject_title'   => 'Logic Circuits and Switching Theory',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Villanueva',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '13:30:00',
                'end_time'        => '15:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 203L',
                'subject_title'   => 'Logic Circuits Lab',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Villanueva',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '07:30:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'ENGG 201',
                'subject_title'   => 'Engineering Economics',
                'section'         => 'BSCPE 2-2',
                'instructor_name' => 'Prof. Aquino',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],

            // BSCPE 3-1 (3rd Year) 
            [
                'room_name'       => 'CPE Laboratory 2',
                'subject_code'    => 'CMPE 301',
                'subject_title'   => 'Embedded Systems',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Dela Cruz',
                'day_of_week'     => DayOfWeek::Monday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 302',
                'subject_title'   => 'Computer Organization and Architecture',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Fernandez',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 302',
                'subject_title'   => 'Computer Organization and Architecture',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Fernandez',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 303',
                'subject_title'   => 'Digital Signal Processing',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Mendoza',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '13:00:00',
                'end_time'        => '16:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'ENGG 301',
                'subject_title'   => 'Engineering Ethics',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Castillo',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '10:30:00',
                'end_time'        => '12:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 304',
                'subject_title'   => 'Operating Systems',
                'section'         => 'BSCPE 3-1',
                'instructor_name' => 'Prof. Ramos',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],

            // BSCPE 4-2 (4th Year, Section 2)
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 401',
                'subject_title'   => 'CPE Practice and Design 1',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Aguilar',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 401',
                'subject_title'   => 'CPE Practice and Design 1',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Aguilar',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 403',
                'subject_title'   => 'Field Trip and Seminars',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Soriano',
                'day_of_week'     => DayOfWeek::Monday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 403',
                'subject_title'   => 'Field Trip and Seminars',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Soriano',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '09:00:00',
                'end_time'        => '10:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 404',
                'subject_title'   => 'Secure Data Management',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Velasco',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '13:00:00',
                'end_time'        => '16:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 405',
                'subject_title'   => 'Emerging Technologies in Computer Engineering',
                'section'         => 'BSCPE 4-2',
                'instructor_name' => 'Prof. Pascual',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],

            // BSCPE 4-3 (4th Year, Section 3) — mirrors reference image 
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 402',
                'subject_title'   => 'CPE Practice and Design 2',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Aguilar',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 402',
                'subject_title'   => 'CPE Practice and Design 2',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Aguilar',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 403',
                'subject_title'   => 'Field Trip and Seminars',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Soriano',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'CMPE 403',
                'subject_title'   => 'Field Trip and Seminars',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Soriano',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '07:30:00',
                'end_time'        => '09:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 406',
                'subject_title'   => 'Software Design',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Reyes',
                'day_of_week'     => DayOfWeek::Tuesday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 1',
                'subject_code'    => 'GEED 201',
                'subject_title'   => 'Gender and Society',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Santos',
                'day_of_week'     => DayOfWeek::Wednesday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'GEED 202',
                'subject_title'   => 'Ethics and Governance',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Torres',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '10:30:00',
                'end_time'        => '13:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 404',
                'subject_title'   => 'Secure Data Management',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Velasco',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '14:30:00',
                'end_time'        => '16:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 1',
                'subject_code'    => 'CMPE 404',
                'subject_title'   => 'Secure Data Management',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Velasco',
                'day_of_week'     => DayOfWeek::Thursday,
                'start_time'      => '18:00:00',
                'end_time'        => '21:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 2',
                'subject_code'    => 'CMPE 301',
                'subject_title'   => 'Embedded Systems',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Dela Cruz',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '15:00:00',
                'end_time'        => '18:00:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 2',
                'subject_code'    => 'CMPE 301',
                'subject_title'   => 'Embedded Systems',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Dela Cruz',
                'day_of_week'     => DayOfWeek::Friday,
                'start_time'      => '18:00:00',
                'end_time'        => '21:00:00',
            ],
            [
                'room_name'       => 'CPE Lecture Room 2',
                'subject_code'    => 'CMPE 405',
                'subject_title'   => 'Emerging Technologies in Computer Engineering',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Pascual',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '13:30:00',
                'end_time'        => '16:30:00',
            ],
            [
                'room_name'       => 'CPE Laboratory 3',
                'subject_code'    => 'CMPE 402',
                'subject_title'   => 'CPE Practice and Design 2',
                'section'         => 'BSCPE 4-3',
                'instructor_name' => 'Prof. Aguilar',
                'day_of_week'     => DayOfWeek::Saturday,
                'start_time'      => '18:00:00',
                'end_time'        => '21:00:00',
            ],
        ];

        foreach ($schedules as $data) {
            $roomId = $rooms->get($data['room_name']);

            if (! $roomId) {
                $this->command->warn("Skipping — room \"{$data['room_name']}\" not found.");
                continue;
            }

            Schedule::create([
                'academic_term_id' => $term->id,
                'room_id'          => $roomId,
                'subject_code'     => $data['subject_code'],
                'subject_title'    => $data['subject_title'],
                'section'          => $data['section'],
                'instructor_name'  => $data['instructor_name'],
                'day_of_week'      => $data['day_of_week'],
                'start_time'       => $data['start_time'],
                'end_time'         => $data['end_time'],
                'is_active'        => true,
                'created_by'       => $adminId,
                'updated_by'       => $adminId,
            ]);
        }
    }
}
