import type {
    FloorplanBox,
    FloorplanLabeledBox,
    FloorplanMainStair,
    FloorplanRoomLayout,
    FloorplanServiceArea,
    FloorplanStair,
} from './floorplan-types';

/**
 * Manual editing guide:
 * x = left/right position
 * y = up/down position
 * w = width
 * h = height
 * fs = label font size
 *
 * Important: keep each room id stable. Laravel room_id must match the id here.
 */
export const floorplanRooms: FloorplanRoomLayout[] = [
    {
        id: 'ece_lab_306b',
        category: 'valid',
        label: ['ECE', 'LAB.', '306B'],
        shape: 'rect',
        x: 160,
        y: 35,
        w: 90,
        h: 150,
        fs: 12,
    },
    {
        id: 'electronic_workshop_lab_306a',
        category: 'valid',
        label: ['ELECTRONIC', 'WORKSHOP', 'LABORATORY', '306A'],
        shape: 'rect',
        x: 250,
        y: 35,
        w: 210,
        h: 150,
        fs: 12,
    },
    {
        id: 'ece_research_development_305b',
        category: 'valid',
        label: ['ECE', 'RESEARCH', 'AND', 'DEVELOPMENT', 'UNIT', '305B'],
        shape: 'rect',
        x: 460,
        y: 35,
        w: 100,
        h: 150,
        fs: 9,
    },
    {
        id: 'electronics_fundamental_lab_1_305a',
        category: 'valid',
        label: ['ELECTRONICS', 'FUNDAMENTAL', 'LAB-1', '305A'],
        shape: 'rect',
        x: 560,
        y: 35,
        w: 175,
        h: 150,
        fs: 12,
    },
    {
        id: 'ece_students_society_304b',
        category: 'valid',
        label: ['ECE', "STUDENT'S", 'SOCIETY', '304B'],
        shape: 'rect',
        x: 735,
        y: 35,
        w: 85,
        h: 150,
        fs: 9,
    },
    {
        id: 'electronics_fundamental_lab_2_304a',
        category: 'valid',
        label: ['ELECTRONICS', 'FUNDAMENTAL', 'LAB-2', '304A'],
        shape: 'rect',
        x: 820,
        y: 35,
        w: 190,
        h: 150,
        fs: 12,
    },
    {
        id: 'pup_help_assist_mobilize_303b',
        category: 'valid',
        label: ['PUP', 'HELP', 'ASSIST', 'AND', 'MOBILIZE', '303B'],
        shape: 'rect',
        x: 1010,
        y: 35,
        w: 105,
        h: 150,
        fs: 9,
    },
    {
        id: 'tv_radio_communication_lab_303a',
        category: 'valid',
        label: ['TV AND', 'RADIO', 'COMMUNICATION', 'LABORATORY', '303A'],
        shape: 'rect',
        x: 1115,
        y: 35,
        w: 190,
        h: 150,
        fs: 12,
    },
    {
        id: 'computer_control_lab_302',
        category: 'valid',
        label: ['COMPUTER', 'CONTROL', 'LABORATORY', '302'],
        shape: 'rect',
        x: 1305,
        y: 35,
        w: 145,
        h: 150,
        fs: 11,
    },
    {
        id: 'lecture_room_307',
        category: 'valid',
        label: ['LECTURE ROOM', '307'],
        shape: 'rect',
        x: 20,
        y: 255,
        w: 130,
        h: 95,
        fs: 12,
    },
    {
        id: 'automatic_control_lab_308',
        category: 'valid',
        label: ['AUTOMATIC', 'CONTROL', 'LABORATORY', '308'],
        shape: 'polygon',
        points: '20,350 150,350 150,455 120,455 120,520 20,520',
        x: 20,
        y: 350,
        w: 130,
        h: 170,
        labelX: 78,
        labelY: 430,
        fs: 11,
    },
    {
        id: 'cea_ssrd',
        category: 'office',
        label: ['CEA-SSRD'],
        shape: 'rect',
        x: 215,
        y: 255,
        w: 160,
        h: 95,
        fs: 12,
    },
    {
        id: 'special_projects_office',
        category: 'office',
        label: ['SPECIAL', 'PROJECTS', 'OFFICE'],
        shape: 'rect',
        x: 215,
        y: 350,
        w: 160,
        h: 95,
        fs: 12,
    },
    {
        id: 'es_dept_office',
        category: 'office',
        label: ['ES DEPT.', 'OFFICE'],
        shape: 'rect',
        x: 600,
        y: 255,
        w: 165,
        h: 88,
        fs: 14,
    },
    {
        id: 'ece_dept_office',
        category: 'office',
        label: ['ECE DEPT.', 'OFFICE'],
        shape: 'rect',
        x: 600,
        y: 343,
        w: 165,
        h: 88,
        fs: 14,
    },
    {
        id: 'coe_dept_office',
        category: 'office',
        label: ['CoE DEPT.', 'OFFICE'],
        shape: 'rect',
        x: 600,
        y: 431,
        w: 165,
        h: 89,
        fs: 14,
    },
    {
        id: 'electronics_workshop_318',
        category: 'valid',
        label: ['ELECTRONICS', 'WORKSHOP', '318'],
        shape: 'polygon',
        points: '1300,310 1420,310 1420,520 1390,520 1390,555 1300,555',
        x: 1300,
        y: 310,
        w: 120,
        h: 245,
        labelX: 1358,
        labelY: 430,
        fs: 12,
    },
    {
        id: 'lecture_room_301',
        category: 'valid',
        label: ['LECTURE', 'ROOM', '301'],
        shape: 'rect',
        x: 1480,
        y: 255,
        w: 100,
        h: 95,
        fs: 10,
    },
    {
        id: 'microcomputer_lab_317',
        category: 'valid',
        label: ['MICROCOMPUTER', 'LABORATORY', '317'],
        shape: 'rect',
        x: 1480,
        y: 350,
        w: 100,
        h: 170,
        fs: 11,
    },
    {
        id: 'personal_computer_lab_1_310',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-1', '310'],
        shape: 'rect',
        x: 160,
        y: 590,
        w: 185,
        h: 115,
        fs: 12,
    },
    {
        id: 'personal_computer_lab_2_311',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-2', '311'],
        shape: 'rect',
        x: 345,
        y: 590,
        w: 185,
        h: 115,
        fs: 12,
    },
    {
        id: 'personal_computer_lab_3_312',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-3', '312'],
        shape: 'rect',
        x: 530,
        y: 590,
        w: 190,
        h: 115,
        fs: 12,
    },
    {
        id: 'personal_computer_lab_4_313',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-4', '313'],
        shape: 'rect',
        x: 720,
        y: 590,
        w: 185,
        h: 115,
        fs: 12,
    },
    {
        id: 'personal_computer_lab_5_314',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-5', '314'],
        shape: 'rect',
        x: 905,
        y: 590,
        w: 190,
        h: 115,
        fs: 12,
    },
    {
        id: 'personal_computer_lab_6_315',
        category: 'valid',
        label: ['PERSONAL', 'COMPUTER', 'LAB-6', '315'],
        shape: 'rect',
        x: 1095,
        y: 590,
        w: 190,
        h: 115,
        fs: 12,
    },
    {
        id: 'digital_circuit_lab_316',
        category: 'valid',
        label: ['DIGITAL', 'CIRCUIT', 'LABORATORY', '316'],
        shape: 'rect',
        x: 1285,
        y: 590,
        w: 165,
        h: 115,
        fs: 11,
    },
];

export const floorplanCorridors: FloorplanBox[] = [
    { x: 115, y: 185, w: 1365, h: 70 },
    { x: 150, y: 520, w: 1330, h: 70 },
    { x: 150, y: 255, w: 65, h: 265 },
    { x: 1420, y: 255, w: 60, h: 335 },
    { x: 765, y: 185, w: 65, h: 335 },
];

export const floorplanCourts: FloorplanLabeledBox[] = [
    { label: ['OPEN', 'COURT'], x: 375, y: 255, w: 225, h: 265, fs: 15 },
    { label: ['OPEN', 'COURT'], x: 940, y: 255, w: 360, h: 265, fs: 15 },
];

export const floorplanToilets: FloorplanLabeledBox[] = [
    { label: ['FEMALE', 'TOILET'], x: 20, y: 90, w: 95, h: 135, fs: 9 },
    { label: ['MALE', 'TOILET'], x: 20, y: 590, w: 130, h: 80, fs: 9 },
    { label: ['FEMALE', 'TOILET'], x: 1495, y: 90, w: 85, h: 135, fs: 9 },
    { label: ['MALE', 'TOILET'], x: 1480, y: 590, w: 100, h: 80, fs: 9 },
];

export const floorplanServiceAreas: FloorplanServiceArea[] = [
    { kind: 'service', label: ['TOOL', 'ROOM'], x: 75, y: 520, w: 75, h: 70, fs: 9 },

    // Darkened rooms. These remain visible as blocks, but no labels are shown.
    { kind: 'ignored', label: [], x: 790, y: 255, w: 78, h: 78, fs: 0 },
    { kind: 'ignored', label: [], x: 868, y: 255, w: 52, h: 78, fs: 0 },
];

export const floorplanSideStairs: FloorplanStair[] = [
    { kind: 'emergency', x: 115, y: 90, w: 45, h: 135, direction: 'horizontal', lines: 11 },
    { kind: 'emergency', x: 1450, y: 90, w: 45, h: 135, direction: 'horizontal', lines: 11 },
    { kind: 'side', x: 215, y: 445, w: 160, h: 75, direction: 'vertical', lines: 12 },
    { kind: 'side', x: 1300, y: 255, w: 120, h: 55, direction: 'vertical', lines: 12 },
];

export const floorplanMainStair: FloorplanMainStair = {
    x: 790,
    y: 345,
    w: 92,
    h: 96,
    curveW: 43,
    curveR: 48,
    lines: 10,
};
